In [2]:
import pandas as pd

# Load Five CSV Files

In [4]:
customers = pd.read_csv("../data/raw/customer.csv")

products = pd.read_csv("../data/raw/products.csv")

orders = pd.read_csv("../data/raw/orders.csv")

order_items = pd.read_csv("../data/raw/order_items.csv")

payments = pd.read_csv("../data/raw/payments.csv")

# Check the Dimensions

In [7]:
print("customers :",customers.shape)
print("products :",products.shape)
print("orders :",orders.shape)
print("order_items :",order_items.shape)
print("payments :",payments.shape)

customers : (5000, 9)
products : (500, 7)
orders : (20000, 5)
order_items : (49956, 9)
payments : (20000, 6)

# Inspecting Dataset

In [9]:
display(customers.head())
display(products.head())
display(orders.head())
display(order_items.head())
display(payments.head())

,customer_id,first_name,last_name,gender,age,city,country,signup_date,email
0,C00001,Emma,Johnson,Female,44,Abu Dhabi,UAE,2025-12-29,emma.johnson00001@gmail.com
1,C00002,Ali,Rahman,Male,41,Abu Dhabi,UAE,2026-03-16,ali.rahman00002@gmail.com
2,C00003,Mohammed,Martin,Female,33,Dubai,UAE,2026-06-17,mohammed.martin00003@gmail.com
3,C00004,John,Moore,Male,46,Abu Dhabi,UAE,2024-07-22,john.moore00004@gmail.com
4,C00005,Emma,Davis,Female,62,Abu Dhabi,UAE,2026-06-26,emma.davis00005@gmail.com

,product_id,product_name,category,sub_category,price,cost,profit_per_unit
0,P00001,Skincare Product 1,Beauty,Skincare,494.89,262.21,232.68
1,P00002,Laptops Product 2,Electronics,Laptops,591.51,400.54,190.97
2,P00003,Skincare Product 3,Beauty,Skincare,632.53,429.25,203.28
3,P00004,Skincare Product 4,Beauty,Skincare,1176.05,833.18,342.87
4,P00005,Bags Product 5,Fashion,Bags,806.78,427.31,379.47

  order_id customer_id order_status orders_date shipping_city
0   O00001      C02846    Delivered  2025-11-18         Dubai
1   O00002      C00980    Delivered  2026-01-21         Dubai
2   O00003      C03007    Delivered  2026-04-08       Sharjah
3   O00004      C04220    Delivered  2026-02-15       Sharjah
4   O00005      C04939    Delivered  2025-06-05       Sharjah

,order_item_id,order_id,product_id,quantity,unit_price,discount,gross_amount,discount_amount,total_amount
0,OI000001,O00001,P00132,5,1228.66,0,6143.30,0.00,6143.30
1,OI000002,O00001,P00378,5,334.54,0,1672.70,0.00,1672.70
2,OI000003,O00001,P00319,3,410.69,20,1232.07,246.41,985.66
3,OI000004,O00001,P00364,5,1877.20,0,9386.00,0.00,9386.00
4,OI000005,O00002,P00070,1,741.02,0,741.02,0.00,741.02

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
0,PAY000001,O00001,2025-11-18,Bank Transfer,Completed,18187.66
1,PAY000002,O00002,2026-01-21,Cash on Delivery,Completed,5701.41
2,PAY000003,O00003,2026-04-08,Credit Card,Completed,13050.69
3,PAY000004,O00004,2026-02-15,Digital Wallet,Completed,6610.84
4,PAY000005,O00005,2025-06-05,Credit Card,Completed,2104.07

# Insepect Column name and data types

In [15]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5000 non-null   object
 1   first_name   5000 non-null   object
 2   last_name    5000 non-null   object
 3   gender       5000 non-null   object
 4   age          5000 non-null   int64
 5   city         5000 non-null   object
 6   country      5000 non-null   object
 7   signup_date  5000 non-null   object
 8   email        5000 non-null   object
dtypes: int64(1), object(8)
memory usage: 351.7+ KB

In [16]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_id       500 non-null    object
 1   product_name     500 non-null    object
 2   category         500 non-null    object
 3   sub_category     500 non-null    object
 4   price            500 non-null    float64
 5   cost             500 non-null    float64
 6   profit_per_unit  500 non-null    float64
dtypes: float64(3), object(4)
memory usage: 27.5+ KB

In [17]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       20000 non-null  object
 1   customer_id    20000 non-null  object
 2   order_status   20000 non-null  object
 3   orders_date    20000 non-null  object
 4   shipping_city  20000 non-null  object
dtypes: object(5)
memory usage: 781.4+ KB

In [18]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49956 entries, 0 to 49955
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    49956 non-null  object
 1   order_id         49956 non-null  object
 2   product_id       49956 non-null  object
 3   quantity         49956 non-null  int64
 4   unit_price       49956 non-null  float64
 5   discount         49956 non-null  int64
 6   gross_amount     49956 non-null  float64
 7   discount_amount  49956 non-null  float64
 8   total_amount     49956 non-null  float64
dtypes: float64(4), int64(2), object(3)
memory usage: 3.4+ MB

In [19]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      20000 non-null  object
 1   order_id        20000 non-null  object
 2   payment_date    20000 non-null  object
 3   payment_method  20000 non-null  object
 4   payment_status  20000 non-null  object
 5   payment_amount  20000 non-null  float64
dtypes: float64(1), object(5)
memory usage: 937.6+ KB